function output = Pompos(input,M)
M=log2(M)
Es = 1;
fc = 1/4;
Tsample = 1;
Tsymbol = 40;
T = Tsymbol/Tsample;
gt = sqrt(2*Es/Tsymbol);
L = length(input)/2;
ms = zeros(L,2);
symbols = zeros(M,2);
input = reshape(input, 2, L)';
ms=gray2bin(input,'psk',M )
symbols(:,1) = sqrt(Es)*(cos(2*pi/4*(0:(M-1))))';
symbols(:,2) = sqrt(Es)*(sin(2*pi/4*(0:(M-1))))';
M1 = repmat(gt * ms(:,1),1,T)’ .* repmat(gt * ms(:,2),1,T)’;
 M2 = repmat(cos(2*pi*fc*(0:T-1)),L,1)’ .* repmat(sin(2*pi*fc*(0:T1)),L,1)’;
output = reshape(M1 + M2, L * T, 1);